const config = {
	home: '/',
	login: '/login',
	register: '/register',
	station: '/station',
	world: '/world',
	map: '/map',
	contribution: '/contribution',
	programRules: '/programRules',
	profile: '/profile',
	editProfile: '/editProfile',
	donationHistoryPage: '/donationHistoryPage',
	greecoinHistory: '/greecoinHistory',
	recharge: '/recharge',
	forum: '/forum',
	deleteAccount: '/deleteAccount',
	store: '/store',
	storeDetail: '/storeDetail',
	nai: '/nai',
	story: '/story',
	cart: '/cart',
	listOne: '/listOne',
	collection: '/collection',
	checkOrder: '/checkOrder',
	profileV2: '/profileV2',
	order: '/profileV2/orders',
	myOrder: '/profileV2/myOrder',
	404: '*',
};

export default config;
